// work_React/dynamic-table/src/App.js
import React from 'react';

const headers = ['Nombre', 'Apellido', 'Edad', 'Cédula', 'Mayor de edad'];
const rows = [
  ['Juan', 'Pérez', 25, '12345678'],
  ['María', 'González', 17, '87654321'],
  // ... más filas
];

const App = () => {
  const checkAge = (age) => age >= 18 ? 'Sí' : 'No';

  return (
    <table>
      <thead>
        <tr>
          {headers.map((header, index) => <th key={index}>{header}</th>)}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, index) => (
          <tr key={index}>
            {row.map((cell, index) => <td key={index}>{cell}</td>)}
            <td>{checkAge(row[2])}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

export default App;

// work_vue/src/App.vue
<template>
  <div>
    <dynamic-table :headers="headers" :rows="rows"></dynamic-table>
  </div>
</template>

<script>
import DynamicTable from './components/DynamicTable.vue';

export default {
  components: {
    DynamicTable
  },
  data() {
    return {
      headers: ['Nombre', 'Apellido', 'Edad', 'Cédula'],
      rows: [
        ['Juan', 'Pérez', 25, '12345678'],
        ['María', 'González', 17, '87654321'],
        ['Hugo','Fernando',16,'29487248']

        //... más filas si las tienes
      ]
    }
  }
}
</script>
